# Generated by Django 5.0.6 on 2025-04-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_generatedpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(default='default_teacher.jpg', upload_to='teacher_profiles/'),
        ),
    ]
